config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'about' , to: 'welcome#about'
  get 'contact' , to: 'welcome#contact'
  get 'reports' , to: 'greports#index'

resources :greports do
  collection { post :import }
end

  get 'signup' , to: 'users#new'
 #post 'users', to: 'users#create'
 resources :users, except: [:new]

  get 'login' , to: 'sessions#new'
  post 'login' , to:'sessions#create'
  delete 'logout' , to: 'sessions#destroy'
  post 'signup', to: 'sessions#create'

 resources :greports do
  get 'buildlist', on: :new
end
resources :greports do
  collection {delete :destroyall }
  get 'destroyall', on: :new
end

match 'greports/destroyall' => 'greports#destroyall', via: [:get, :post]
resources :greports

end

app/models/greport.rb
class Greport < ActiveRecord::Base
  belongs_to :user
  validates :roll, presence: true
  validates :name, presence: true, length: { minimum: 3, maximum: 20}
  validates :marksobt, presence: true
  validates :marksout, presence: true
  validates :percent, presence: true
  validates :year, presence: true
  validates :exam, presence: true
  validates :sem, presence: true
  validates :session, presence: true
  validates :batch, presence: true
  validates :result, presence: true
  validates :sgpa, presence: true
  #validates :user_id, presence: true

   # def self.import(file)
     # CSV.foreach(file.path, headers: true) do |row|
       # Greport.create! row.to_hash

     # end
  # end
       def self.import(file)
         category_attributes = ["roll","name", "marksobt", "marksout", "percent", "year", "exam", "sem", "session", "batch", "result","sgpa" ]
         CSV.foreach(file.path, headers: true) do |row|
         #item = where(id: row["id"])
          # .first_or_create!(row.to_hash.slice(*category_attributes))
           item = find_by_id(row["id"]) || new
           item.attributes = row.to_hash.slice(*category_attributes)
         item.save!
         end
      end


  def self.total_passed()
    pass=0
      Greport.find_each do |user|
        (
          string = user.result
          if(string == "Pass"|| string == "pass") then
            pass=pass+1
          end
        )
      end
    return pass
  end


  def self.total_failed()
    failed=0
      Greport.find_each do |user|
       (
          string = user.result
          if(string == "Fail"|| string == "fail") then
            failed=failed+1
          end
          )
      end
    return failed
  end


  def self.toppers()
    arrayobj=[]
    x=0
    Greport.all.order(percent: :desc)
    Greport.first(3).each do |user|
        arrayobj[x]=user.percent
        x=x+1
    end
    return arrayobj
  end

    def self.toppernames()
    obarray=[]
    y=0
    Greport.all.order(percent: :desc)
    Greport.first(3).each do |user|
      obarray[y]=user.name
      y=y+1
    end
    return obarray
    end

    def self.destroy
     Greport.delete_all
    end
  end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :greports
  before_save { self.email = email.downcase }
  validates :username, presence: true,
                       length: { minimum: 3, maximum: 25 },
                       uniqueness: { case_sensitive: false}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email , presence: true,length: {maximum: 105}, uniqueness: { case_sensitive: false },
                     format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/greports_controller.rb
class GreportsController < ApplicationController
  before_action :set_greport, only: [:show, :edit, :update, :destroy]

  # GET /greports
  # GET /greports.json
  def index
    @greports = Greport.all
     @toppers=Greport.all.order(percent: :desc).limit(3)
  end

   def buildlist
   end
  # GET /greports/1
  # GET /greports/1.json
  def show

 end


  # GET /greports/new
  def new
    @greport = Greport.new
  end

  # GET /greports/1/edit
  def edit
  end

  # POST /greports
  # POST /greports.json
  def create
    @greport = Greport.new(greport_params)
    @greport.user = User.first

    respond_to do |format|
      if @greport.save
        format.html { redirect_to @greport,  notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @greport }
      else
        format.html { render :new }
        format.json { render json: @greport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /greports/1
  # PATCH/PUT /greports/1.json
  def update
    respond_to do |format|
      if @greport.update(greport_params)
        format.html { redirect_to @greport, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @greport }
      else
        format.html { render :edit }
        format.json { render json: @greport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /greports/1
  # DELETE /greports/1.json
  def destroy
    @destroy=Greport.all
    @destroy.destroy
    #@greport.destroy
    respond_to do |format|
      format.html { redirect_to buildlist_new_greport_path, notice: 'Records were successfully destroyed.You can now create a a new report!' }
      format.json { head :no_content }
    end
  end

  def destroyall
    Greport.destroy
    respond_to do |format|
      format.html { redirect_to buildlist_new_greport_path, notice: 'Records were successfully destroyed.You can now create a a new report!' }
      format.json { head :no_content }
    end
  end

  def import
    Greport.import(params[:file])
    redirect_to(buildlist_new_greport_path,notice: "Imported successfully")
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_greport
      @greport = Greport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def greport_params
      params.require(:greport).permit(:roll, :name, :marksobt, :marksout, :percent, :year, :exam, :sem, :session, :batch, :result, :sgpa)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to about_path

     else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
  end
  end

  def destroy
    session[:user_id]=nil
    flash[:danger] = "You have logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success]="Welcome to Result Analytics #{@user.username}"
      redirect_to greports_path
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def reports
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greports_helper.rb
module GreportsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/greports/_form.html.erb
<%= render 'shared/errors', obj: @greport %>
<%= form_for(@greport) do |f| %>
<div class = "row">
  <div class =" col-md-6">
   <div class="field">
    <%= f.label :roll %><br>
    <%= f.text_field :roll %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :marksobt %><br>
    <%= f.text_field :marksobt %>
  </div>
  <div class="field">
    <%= f.label :marksout %><br>
    <%= f.text_field :marksout %>
  </div>
  <div class="field">
    <%= f.label :result %><br>
    <%= f.text_field :result %>
  </div>
  <div class="field">
    <%= f.label :sgpa %><br>
    <%= f.text_field :sgpa %>
  </div>
  </div>
  <div class =" col-md-6">
    <div class="field">
    <%= f.label :percent %><br>
    <%= f.text_field :percent %>
  </div>
    <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
    <div class="field">
    <%= f.label :exam %><br>
    <%= f.text_field :exam %>
  </div>
    <div class="field">
    <%= f.label :sem %><br>
    <%= f.text_field :sem %>
  </div>
    <div class="field">
    <%= f.label :session %><br>
    <%= f.text_field :session %>
  </div>
    <div class="field">
    <%= f.label :batch %><br>
    <%= f.text_field :batch %>
  </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/greports/buildlist.html.erb
    <div class="media">
      <div class="media-body">
        <h2>Import Data</h2>
        <%= form_tag  import_greports_path, multipart: true do %>
        <%= file_field_tag :file %><br>
        <%= submit_tag "Import" %>
        <% end %><br>
        <div>
          <%= link_to "Generate Report", greports_path, class: "btn btn-success btn-lg btn-xlarge" %>
          <%= link_to "View Previous Report", greports_path, class: "btn btn-primary.outline btn-lg btn-xlarge" %>
        </div>
      </div>
    </div>
  </div>

app/views/greports/edit.html.erb
<h1>Editing Greport</h1>

<%= render 'form' %>

<%= link_to 'Show', @greport %> |
<%= link_to 'Back', greports_path %>

app/views/greports/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-xs-6">
     <div id="container" style="width:100%; height:400px;">
       <h3>Hello, welcome!</h3>
       <p style="font-size: 160%;"> This is your reports page. This is your generated report.To the right we have the pie chart representation of the passed vs the failed students in the examination.To the lower side you will find the list of the first 3 toppers of the examination.At this stage,we only have two options and later we will be implementing dynamic report generation by choosing the fields of your choice !So Let's report it!</p>

    </div>
  </div>
  <div class = "col-xs-6">
    <div id="container1" style="width:100%; height:400px;">
    </div>
  </div>
</div>


<div class="row">
 <div class="container">
    <div class="col-cs-6">
        <script>
          $(function () {
            $('#container1').highcharts({
                chart: {
                    type: 'pie'
                },
                title: {
                    text: 'Students Result'
                },
                xAxis: {
                    categories: ['Pass','Fail']
                  //categories: ['Apples', 'Bananas', 'Oranges']
                },
                yAxis: {
                    title: {
                        text: 'Passed Students'
                    }
                },
              tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    }
                }
            }
        },

                series: [{

                    data:[{
                      name: 'Passed',
                      y: <%=  Greport.total_passed().to_i %>
                }, {
                    name: 'Failed',
                    y:  <%= Greport.total_failed().to_i  %>
                }]
                }]
            });
        });
        </script>
    </div>
  </div>
  <div class="container">
    <div class="col-sx-6">
     <script>

      </script>
<style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
    background-color: #4CAF50;
    color: white;
}
</style>


<h2> Student Toppers<h2>

      <table border="I">
        <thead>
          <tr>
            <th>Roll No.</th>
            <th>Names</th>
            <th>Percentage</th>
            <th>Exam</th>
          </tr>
        </thead>
      <% @toppers.each do |topper| %>
      <tr>
        <td><%= topper.roll.to_i %></td>
        <td><%= topper.name %></td>
        <td><%= topper.percent %>%</td>
        <td><%= topper.exam %></td>
      </tr>
        <% end %>
      </table>

  </div>
</div>
</div>
<!--<h1>Generate Reports</h1>
<div class="media">
  <div class="media-body">
    <table class="table table-hover">
  <thead>
    <tr>
      <th>Roll</th>
      <th>Name</th>
      <th>Marks obtained</th>
      <th>Marks outof</th>
      <th>Percent</th>
      <th>Year</th>
      <th>Exam</th>
      <th>Sem</th>
      <th>Session</th>
      <th>Batch</th>
      <th>Result</th>
      <th>Sgpa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @greports.each do |greport| %>
      <tr>
        <td><%= greport.roll %></td>
        <td><%= greport.name %></td>
        <td><%= greport.marksobt %></td>
        <td><%= greport.marksout %></td>
        <td><%= greport.percent %></td>
        <td><%= greport.year %></td>
        <td><%= greport.exam %></td>
        <td><%= greport.sem %></td>
        <td><%= greport.session %></td>
        <td><%= greport.batch %></td>
        <td><%= greport.result %></td>
        <td><%= greport.sgpa %></td>
        <td><%= link_to 'Show', greport %></td>
        <td><%= link_to 'Edit', edit_greport_path(greport) %></td>
        <td><%= link_to 'Destroy', greport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<br>-->

<!--<div class="media">
  <div class="media-body">
<h2>Import Data</h2>
  <%= form_tag  import_greports_path, multipart: true do %>
  <%= file_field_tag :file %><br>
  <%= submit_tag "Import" %>
<% end %><br>-->
    [ <%= link_to 'Add new Record', new_greport_path %> ]

    <div class="container">

 <p align ="center"><%= link_to "Create a New Report", destroyall_new_greport_path, class: "btn btn-success btn-lg btn-xlarge-shubham" %></p>
      <p><h3 align="center">By clicking this button the previous data will be deleted and you will be redirected to create a new report.We recommend you to print this page for later references.</h3>(You can do it by ctrl+p on your keyboard)</p>
    </div>
      </div>
    </div>

</div>

app/views/greports/new.html.erb
<div class = "col-xs-offset-3">
  <h2>Add New Record</h2>
</div>

<%= render 'form' %>

<div class = "col-xs-4 col-xs-offset-4">
  [<%= link_to 'Cancel entry and go back to listing of records.', greports_path %>]
</div>

app/views/greports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Roll:</strong>
  <%= @greport.roll %>
</p>

<p>
  <strong>Name:</strong>
  <%= @greport.name %>
</p>

<p>
  <strong>Marksobt:</strong>
  <%= @greport.marksobt %>
</p>

<p>
  <strong>Marksout:</strong>
  <%= @greport.marksout %>
</p>

<p>
  <strong>Result:</strong>
  <%= @greport.result %>
</p>

<p>
  <strong>Sgpa:</strong>
  <%= @greport.sgpa %>
</p>
<p>
  <strong>Percent:</strong>
  <%= @greport.percent %>
</p>
<p>
  <strong>Year:</strong>
  <%= @greport.year %>
</p>
<p>
  <strong>Exam:</strong>
  <%= @greport.exam %>
</p>
<p>
  <strong>Sem:</strong>
  <%= @greport.sem %>
</p>
<p>
  <strong>Session:</strong>
  <%= @greport.session %>
</p>
<p>
  <strong>Batch:</strong>
  <%= @greport.batch %>
</p>
<%= link_to 'Edit', edit_greport_path(@greport) %> |
<%= link_to 'Back', greports_path %>

app/views/layouts/_footer.html.erb
<div class = "container">
  <div class ="footer">
    <small>
      Copyright &copy; <a href="https://www.cscreed.com"> Result Analysis System</a>
      by <b>Group 12</b>
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </nav>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<div class ="row">
  <div class= "col-xs-10 col-xs-offset-1">
  <% flash.each do |name, message| %>
    <div class='alert alert-<%= "#{name}" %>'>
      <a href="#" class= "close" data-dismiss="alert" >&#215;</a>
      <%= content_tag :div, message, :id => "flash_#{name}" if message.is_a?(String) %>
    </div>
<% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Result Analytics", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About Us", about_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Generate Reports", buildlist_new_greport_path %></li>
        <% end %>
        <!--<li><%= link_to "Contact Us" , contact_path %></li>-->
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
            <li><%= link_to "Log Out", logout_path, method: :delete %></li>
        <% else %>
             <li><%= link_to "Log In", login_path %></li>
             <li><%= link_to "Sign Up", signup_path %></li>
        <% end %>


      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reportapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="http://code.highcharts.com/highcharts.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>
<div class ="container">
  <%= yield %>
 </div>
<%= render 'layouts/footer' %>
  
</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class = "row">
  <div class = "col-xs-8 col-xs-offset-2">
    <div class ="panel  panel-danger">
      <div class ="panel-heading">
        <h2 class = "panel-title">
       <%= pluralize(obj.errors.count, "error") %> prohibited this report from being saved:</h2>
        <div class ="panel-body">
          <ul>
            <% obj.errors.full_messages.each do |message| %>
            <li><%= message %></li>
           <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
 </div>
<% end %>

app/views/users/new.html.erb
<h1 align="center">Sign Up For Result Analytics</h1>
<%= render 'shared/errors', obj: @user %>
<div class = "row">
  <div class =" col-xs-12">
      <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>

    <div class="form-group">
      <div class ="control-label col-sm-2">
        <%= f.label :username %><br>
      </div>
      <div class ="col-sm-8">
      <%= f.text_field :username, class: "form-control", placeholder: "Enter Username", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class ="control-label col-sm-2">
        <%= f.label :email %><br>
      </div>
       <div class ="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter your email", autofocus: true %>
      </div>
    </div>
   <div class="form-group">
      <div class ="control-label col-sm-2">
        <%= f.label :password %><br>
     </div>
     <div class ="col-sm-8">
      <%= f.password_field :password, class: "form-control", placeholder: "Enter password", autofocus: true %>
     </div>
    </div>

    <div class="actions">
      <div class = "form-group">
        <div class = "col-sm-offset-2 col-sm-10">
          <%= f.submit "Sign Up", class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    </div>
<% end %>

app/views/welcome/about.html.erb
    <!-- Page Content -->
    <div class="container">

        <!-- Jumbotron Header -->
        <header class="jumbotron hero-spacer">
            <h1>A Warm Welcome!</h1>
            <p>Get Started! Know what we do!</p>
            <p><a class="btn btn-primary btn-large">Take a Tour</a>
            </p>
        </header>

        <hr>

        <!-- Title -->
        <div class="row">
            <div class="col-lg-12">
                <h3>Features</h3>
            </div>
        </div>
        <!-- /.row -->

        <!-- Page Features -->
        <div class="row text-center">

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <%= image_tag 'feature1.png' %>
                    <div class="caption">
                        <h3>Beautiful Report Presentations!</h3>
                        <p>We create your reports in an interesting way than the age old table method by generating your report in the form of charts,histograms,tables and lot more!</p>

                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                   <%= image_tag 'feature2.jpg' %>
                    <div class="caption">
                        <h3>Blazing  FAST query processing!</h3>
                        <p>We have the best query processing logic implemeted, that enables you to view your report in a matter of a click.Yes, all it takes is a click to view your report. Try it now!</p>

                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <%= image_tag 'header_imageab.jpg' %>
                    <div class="caption">
                        <h3>Clean Code</h3>
                        <p>We appreciate your time is money and so is ours.Thus we develop the application with clean code so that you get the best experience while using our application.</p>

                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <%= image_tag 'feature4.jpg' %>
                    <div class="caption">
                        <h3>Amazing User Experince!</h3>
                        <p>We have an amazing user interface that is fast,awesome and reliable.And yes,it's accurate too! So enjoy the fast and easy to use UI at result analytics even while enjoying your favourite coffee! It's that simple.</p>

                    </div>
                </div>
            </div>

        </div>
        <!-- /.row -->

        <hr>


    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/index.html.erb
<div class = "center jumbotron" >
  <div class= "container">
  <h1><b>Result Analytics</b></h1>
  <%= link_to "Sign up now ", "signup", class: "btn btn-danger btn-lg btn-xlarge" %>
  </div>
</div>

app/views/welcome/reports.html.erb
<h1>Welcome#reports</h1>
<p>Find me in app/views/welcome/reports.html.erb</p>